#!/bin/bash
#===-                           S C R I P T  T.V.
#===-                           https://script.tv
#===-
#===-            Copyright (C) 2017-2024 Script Network
#===-            Copyright (C) 2017-2024 manicberet@gmail.com
#===-
#===-                      GNU GENERAL PUBLIC LICENSE
#===-                       Version 3, 29 June 2007
#===-
#===-    This program is free software: you can redistribute it and/or modify
#===-    it under the terms of the GPLv3 License as published by the Free
#===-    Software Foundation.
#===-
#===-    This program is distributed in the hope that it will be useful,
#===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
#===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#===-
#===-    You should have received a copy of the General Public License
#===-    along with this program, see LICENCE file.
#===-    see https://www.gnu.org/licenses
#===-
#===----------------------------------------------------------------------------
#===-

repl=`cat /etc/apt/sources.list | grep "^deb .*bian/ *buster .*" | sed "s#^\(deb .*bian/ *\)buster \(.*\)#\1bullseye \2#"`
echo $repl > /etc/apt/sources.list.d/us.list

cat << EOF > /etc/apt/preferences.d/us
Package: libc6-dev
Pin: release n=bullseye
Pin-Priority: 900

Package: g++
Pin: release n=bullseye
Pin-Priority: 900
EOF

export DEBIAN_FRONTEND=noninteractive

apt update

apt remove  -y libgcc-8-dev
apt install  -y -o Dpkg::Options::=--force-confold g++ build-essential
apt -y autoremove

