#!/bin/bash
#===-                           S C R I P T  T.V.
#===-                           https://script.tv
#===-
#===-            Copyright (C) 2017-2024 Script Network
#===-            Copyright (C) 2017-2024 manicberet@gmail.com
#===-
#===-                      GNU GENERAL PUBLIC LICENSE
#===-                       Version 3, 29 June 2007
#===-
#===-    This program is free software: you can redistribute it and/or modify
#===-    it under the terms of the GPLv3 License as published by the Free
#===-    Software Foundation.
#===-
#===-    This program is distributed in the hope that it will be useful,
#===-    but WITHOUT ANY WARRANTY; without even the implied warranty of
#===-    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#===-
#===-    You should have received a copy of the General Public License
#===-    along with this program, see LICENCE file.
#===-    see https://www.gnu.org/licenses
#===-
#===----------------------------------------------------------------------------
#===-

echo "generating keys"

read -r priv_a public_a <<< $(LD_LIBRARY_PATH=../../gov:/usr/lib ./generate_keys)
read -r priv_b public_b <<< $(LD_LIBRARY_PATH=../../gov:/usr/lib ./generate_keys)


echo "A: priv_a ${priv_a} public_a ${public_a}"
echo "B: priv_b ${priv_b} public_b ${public_b}"

bcv="jdk15to18-1.78.1"
libs="../../sdk/wallet/java"
libspath="${libs}:${libs}/libs_bouncy/bcprov-${bcv}.jar:${libs}/libs_bouncy/bcpkix-${bcv}.jar:${libs}/libs_bouncy/bcpg-${bcv}.jar:${libs}/libs_bouncy/bctls-${bcv}.jar:${libs}/libs_bouncy/bcmail-${bcv}.jar"
depjar="../../sdk/wallet/java/us-sdk_bc.jar"
classpath=".:${libspath}:${depjar}"

echo "classpath=$classpath"

MESSAGE="$1"
echo "msg=${MESSAGE}"

encrypted=$(LD_LIBRARY_PATH=../../gov:/usr/lib ./test_cpp $priv_a $public_b encrypt "$MESSAGE")
echo "encrypted (C++) ${encrypted}"

decrypted=$(java -cp "${classpath}" Main $priv_b $public_a "decrypt" $encrypted)
echo "decrypted (java) ${decrypted}"

encrypted2=$(java -cp "${classpath}" Main $priv_b $public_a "encrypt" "$MESSAGE")
echo "encrypted (java) ${encrypted2}"

decrypted2=$(LD_LIBRARY_PATH=../../gov:/usr/lib ./test_cpp $priv_a $public_b decrypt $encrypted2)
echo "decrypted (C++) ${decrypted2}"

if [ "$MESSAGE" == "$decrypted" ] && [ "$MESSAGE" == "$decrypted2" ]
then
    echo "PASSED"
else
    echo "FAILED"
fi
