using System.IO;

namespace us.wallet
{
    interface daemon_api : wallet_api, pairing_api, sys_api
    {
//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__functions_wallet_daemon_cs_purevir
//------------------generated by apitool- do not edit
// wallet_daemon - master file: us/apitool/data/wallet_daemon
  void list_protocols(Stream os);
  void trade(string arg0, string arg1, string arg2, Stream os);
  void list_trades(Stream os);
  void kill_trade(byte[] arg0, Stream os);
  void command_trade(byte[] arg0, string arg1, Stream os);
  void command_trade_bin(byte[] arg0, string arg1, Stream os);
  void grid(Stream os);
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit
    }
}
