using System;
using System.IO;

namespace us.wallet
{
    interface pairing_api
    {
//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__functions_pairing_cs_purevir
//------------------generated by apitool- do not edit
// pairing - master file: us/apitool/data/pairing
  void pair(byte[] arg0, string arg1, string arg2, Stream os);
  void unpair(byte[] arg0, Stream os);
  void list_devices(Stream os);
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit

    }
}
