namespace us.wallet
{
    class sys_rpc_api : sys_api
    {
        public sys_rpc_api(rpc_api endpoint_)
        {
            endpoint = endpoint_;
        }

//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__functions_sys_cs_rpc-impl
//------------------generated by apitool- do not edit
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit

        rpc_api endpoint;
    }
}
