namespace us.wallet
{
    interface sys_api
    {
//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../../api/apitool_generated__functions_sys_cs_purevir
//------------------generated by apitool- do not edit
// sys - master file: us/apitool/data/sys
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit

    }
}
